@startuml

' Regular UML diagram
class Button {
    - location: Point
    - image: Image

    + __init__(location: Point, image: Image)
    + draw(): None
    + check_click(mouse_position: Point): bool
}

@enduml

